name: push latest code to the server
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.DEV_PASSWORD }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEV_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh  ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_HOST }} "pwd && whoami && cd /home/ci-cd/airotax/monitoring && git status && git pull && exit" 
